In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
runways = pd.read_csv(
    "../../../data/raw/airports/runways.csv"
)

In [3]:
runways.head()

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
0,269408,6523,00A,80.0,80.0,ASPH-G,1,0,H1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,255155,6524,00AK,2500.0,40.0,GRVL,0,0,N,NaN,NaN,NaN,NaN,NaN,S,NaN,NaN,NaN,NaN,NaN
2,254165,6525,00AL,2100.0,90.0,TURF,0,0,01,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN
3,506792,506791,00AN,4517.0,60.0,GVL,0,0,3,NaN,NaN,NaN,NaN,NaN,21,NaN,NaN,NaN,NaN,NaN
4,322128,322127,00AS,1450.0,60.0,Turf,0,0,1,NaN,NaN,NaN,NaN,NaN,19,NaN,NaN,NaN,NaN,NaN

In [4]:
runways.tail()

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
48069,235186,27243,ZYTX,10499.0,148.0,CON,1,0,06,41.630402,123.469002,171.0,49.0,NaN,24,41.649300,123.498001,197.0,229.0,NaN
48070,235169,27244,ZYYJ,8530.0,148.0,CON,1,0,09,42.881100,129.436005,623.0,81.7,NaN,27,42.884499,129.466995,597.0,261.7,NaN
48071,354997,317861,ZYYK,8202.0,NaN,NaN,0,0,04,NaN,NaN,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,NaN
48072,346789,346788,ZZ-0003,1800.0,15.0,Turf,0,0,15,NaN,NaN,NaN,NaN,NaN,33,NaN,NaN,NaN,NaN,NaN
48073,599953,599952,ZZ-0004,33.0,33.0,NaN,0,0,1,18.855000,77.519000,8530.0,270.0,NaN,19,18.855000,77.519000,8530.0,270.0,NaN

In [5]:
runways.sample(5)

,id,airport_ref,airport_ident,length_ft,width_ft,surface,lighted,closed,le_ident,le_latitude_deg,le_longitude_deg,le_elevation_ft,le_heading_degT,le_displaced_threshold_ft,he_ident,he_latitude_deg,he_longitude_deg,he_elevation_ft,he_heading_degT,he_displaced_threshold_ft
20411,241413,18515,K1S9,3446.0,48.0,ASPH-G,1,0,17,48.318699,-117.741997,NaN,190.0,230.0,35,48.309399,-117.745003,NaN,240.1,101.0
32068,264627,45771,PN82,65.0,65.0,ASPH,0,0,H1,NaN,NaN,NaN,NaN,NaN,H1,NaN,NaN,NaN,NaN,NaN
22599,241689,19796,KF05,4304.0,80.0,ASP,1,0,16,34.231300,-99.286003,1258.0,165.7,NaN,34,34.219799,-99.282501,1259.0,345.7,NaN
32198,251003,24333,PWR,3000.0,400.0,WATER,0,0,NE,NaN,NaN,NaN,NaN,NaN,SW,NaN,NaN,NaN,NaN,NaN
26076,240369,21386,KWWR,5500.0,150.0,PER,0,1,12,NaN,NaN,NaN,120.0,NaN,30,NaN,NaN,NaN,300.0,NaN

In [6]:
print("Rows :", runways.shape[0])
print("Columns :", runways.shape[1])

Rows : 48074
Columns : 20

In [7]:
runways.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48074 entries, 0 to 48073
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         48074 non-null  int64
 1   airport_ref                48074 non-null  int64
 2   airport_ident              48074 non-null  object
 3   length_ft                  47785 non-null  float64
 4   width_ft                   45061 non-null  float64
 5   surface                    47571 non-null  object
 6   lighted                    48074 non-null  int64
 7   closed                     48074 non-null  int64
 8   le_ident                   47831 non-null  object
 9   le_latitude_deg            15663 non-null  float64
 10  le_longitude_deg           15650 non-null  float64
 11  le_elevation_ft            13300 non-null  float64
 12  le_heading_degT            15075 non-null  float64
 13  le_displaced_threshold_ft  3067 non-null   float64
 14  he_ident                   40473 non-null  object
 15  he_latitude_deg            15541 non-null  float64
 16  he_longitude_deg           15543 non-null  float64
 17  he_elevation_ft            13074 non-null  float64
 18  he_heading_degT            16855 non-null  float64
 19  he_displaced_threshold_ft  2826 non-null   float64
dtypes: float64(12), int64(4), object(4)
memory usage: 7.3+ MB

In [8]:
runways.columns

Index(['id', 'airport_ref', 'airport_ident', 'length_ft', 'width_ft',
       'surface', 'lighted', 'closed', 'le_ident', 'le_latitude_deg',
       'le_longitude_deg', 'le_elevation_ft', 'le_heading_degT',
       'le_displaced_threshold_ft', 'he_ident', 'he_latitude_deg',
       'he_longitude_deg', 'he_elevation_ft', 'he_heading_degT',
       'he_displaced_threshold_ft'],
      dtype='object')

In [9]:
missing = pd.DataFrame({
    "Missing Values": runways.isnull().sum(),
    "Percentage": (
        runways.isnull().mean() * 100
    ).round(2)
})

missing.sort_values(
    by="Percentage",
    ascending=False
)

                           Missing Values  Percentage
he_displaced_threshold_ft           45248       94.12
le_displaced_threshold_ft           45007       93.62
he_elevation_ft                     35000       72.80
le_elevation_ft                     34774       72.33
le_heading_degT                     32999       68.64
he_longitude_deg                    32531       67.67
he_latitude_deg                     32533       67.67
le_longitude_deg                    32424       67.45
le_latitude_deg                     32411       67.42
he_heading_degT                     31219       64.94
he_ident                             7601       15.81
width_ft                             3013        6.27
surface                               503        1.05
length_ft                             289        0.60
le_ident                              243        0.51
id                                      0        0.00
airport_ident                           0        0.00
airport_ref                             0        0.00
lighted                                 0        0.00
closed                                  0        0.00

In [10]:
print(
    "Duplicate Rows:",
    runways.duplicated().sum()
)

Duplicate Rows: 0

In [11]:
runways["id"].duplicated().sum()

np.int64(0)