In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

temperature = pd.read_csv("../../data/raw/weather/temperature.csv")

print("Temperature Dataset Loaded Successfully!")

Temperature Dataset Loaded Successfully!

In [3]:
temperature.head()

,datetime,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,Denver,San Antonio,Dallas,Houston,Kansas City,Minneapolis,Saint Louis,Chicago,Nashville,Indianapolis,Atlanta,Detroit,Jacksonville,Charlotte,Miami,Pittsburgh,Toronto,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
0,2012-10-01 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309.100000,NaN,NaN,NaN
1,2012-10-01 13:00:00,284.630000,282.080000,289.480000,281.800000,291.870000,291.530000,293.410000,296.600000,285.120000,284.610000,289.290000,289.740000,288.270000,289.980000,286.870000,286.180000,284.010000,287.410000,283.850000,294.030000,284.030000,298.170000,288.650000,299.720000,281.000000,286.260000,285.630000,288.220000,285.830000,287.170000,307.590000,305.470000,310.580000,304.4,304.4,303.5
2,2012-10-01 14:00:00,284.629041,282.083252,289.474993,281.797217,291.868186,291.533501,293.403141,296.608509,285.154558,284.607306,289.303649,289.762974,288.297576,289.997635,286.893636,286.185246,284.054691,287.421360,283.889394,294.035341,284.069789,298.205230,288.650172,299.732518,281.024767,286.262541,285.663208,288.247676,285.834650,287.186092,307.590000,304.310000,310.495769,304.4,304.4,303.5
3,2012-10-01 15:00:00,284.626998,282.091866,289.460618,281.789833,291.862844,291.543355,293.392177,296.631487,285.233952,284.599918,289.338497,289.830767,288.334343,290.038151,286.951401,286.199194,284.177412,287.454637,283.941919,294.049702,284.173965,298.299595,288.650582,299.766579,281.088319,286.269518,285.756824,288.326940,285.847790,287.231672,307.391513,304.281841,310.411538,304.4,304.4,303.5
4,2012-10-01 16:00:00,284.624955,282.100481,289.446243,281.782449,291.857503,291.553209,293.381213,296.654466,285.313345,284.592530,289.373345,289.898560,288.371111,290.078666,287.009166,286.213142,284.300133,287.487914,283.994444,294.064063,284.278140,298.393961,288.650991,299.800641,281.151870,286.276496,285.850440,288.406203,285.860929,287.277251,307.145200,304.238015,310.327308,304.4,304.4,303.5

In [4]:
temperature.tail()

,datetime,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,Denver,San Antonio,Dallas,Houston,Kansas City,Minneapolis,Saint Louis,Chicago,Nashville,Indianapolis,Atlanta,Detroit,Jacksonville,Charlotte,Miami,Pittsburgh,Toronto,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
45248,2017-11-29 20:00:00,NaN,282.00,NaN,280.82,293.55,292.15,289.54,294.71,285.72,289.56,294.70,290.48,295.15,285.33,279.79,285.41,281.34,292.89,285.98,290.04,281.25,296.92,294.15,NaN,285.30,278.74,290.24,NaN,275.13,288.08,NaN,NaN,NaN,NaN,NaN,NaN
45249,2017-11-29 21:00:00,NaN,282.89,NaN,281.65,295.68,292.74,290.61,295.59,286.45,290.70,295.82,291.02,295.82,285.16,280.22,286.01,281.69,292.40,286.17,291.42,281.05,296.92,293.90,NaN,285.33,278.75,289.24,NaN,274.13,286.02,NaN,NaN,NaN,NaN,NaN,NaN
45250,2017-11-29 22:00:00,NaN,283.39,NaN,282.75,295.96,292.58,291.34,296.25,286.44,289.71,296.04,291.15,296.37,285.16,279.92,286.04,281.07,291.65,284.21,291.84,280.17,296.33,292.06,NaN,282.91,277.55,286.78,NaN,273.48,283.94,NaN,NaN,NaN,NaN,NaN,NaN
45251,2017-11-29 23:00:00,NaN,283.02,NaN,282.96,295.65,292.61,292.15,297.15,286.14,289.17,295.28,289.59,294.65,285.36,279.07,285.03,280.06,287.64,283.20,290.64,278.06,294.95,287.58,NaN,280.14,276.16,284.57,NaN,272.48,282.17,NaN,NaN,NaN,NaN,NaN,NaN
45252,2017-11-30 00:00:00,NaN,282.28,NaN,283.04,294.93,291.40,291.64,297.15,284.70,285.18,292.02,287.88,291.44,285.15,278.08,283.44,278.46,285.90,282.78,287.74,276.59,293.15,285.61,NaN,279.19,274.51,283.42,NaN,271.80,280.65,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
temperature.shape

(45253, 37)

In [6]:
temperature.columns

Index(['datetime', 'Vancouver', 'Portland', 'San Francisco', 'Seattle',
       'Los Angeles', 'San Diego', 'Las Vegas', 'Phoenix', 'Albuquerque',
       'Denver', 'San Antonio', 'Dallas', 'Houston', 'Kansas City',
       'Minneapolis', 'Saint Louis', 'Chicago', 'Nashville', 'Indianapolis',
       'Atlanta', 'Detroit', 'Jacksonville', 'Charlotte', 'Miami',
       'Pittsburgh', 'Toronto', 'Philadelphia', 'New York', 'Montreal',
       'Boston', 'Beersheba', 'Tel Aviv District', 'Eilat', 'Haifa',
       'Nahariyya', 'Jerusalem'],
      dtype='str')

In [7]:
temperature.info()

<class 'pandas.DataFrame'>
RangeIndex: 45253 entries, 0 to 45252
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   datetime           45253 non-null  str
 1   Vancouver          44458 non-null  float64
 2   Portland           45252 non-null  float64
 3   San Francisco      44460 non-null  float64
 4   Seattle            45250 non-null  float64
 5   Los Angeles        45250 non-null  float64
 6   San Diego          45252 non-null  float64
 7   Las Vegas          45252 non-null  float64
 8   Phoenix            45250 non-null  float64
 9   Albuquerque        45252 non-null  float64
 10  Denver             45252 non-null  float64
 11  San Antonio        45252 non-null  float64
 12  Dallas             45249 non-null  float64
 13  Houston            45250 non-null  float64
 14  Kansas City        45252 non-null  float64
 15  Minneapolis        45240 non-null  float64
 16  Saint Louis        45252 non-null  float64
 17  Chicago            45250 non-null  float64
 18  Nashville          45251 non-null  float64
 19  Indianapolis       45246 non-null  float64
 20  Atlanta            45247 non-null  float64
 21  Detroit            45252 non-null  float64
 22  Jacksonville       45252 non-null  float64
 23  Charlotte          45250 non-null  float64
 24  Miami              44448 non-null  float64
 25  Pittsburgh         45250 non-null  float64
 26  Toronto            45252 non-null  float64
 27  Philadelphia       45250 non-null  float64
 28  New York           44460 non-null  float64
 29  Montreal           45250 non-null  float64
 30  Boston             45250 non-null  float64
 31  Beersheba          44455 non-null  float64
 32  Tel Aviv District  44460 non-null  float64
 33  Eilat              44461 non-null  float64
 34  Haifa              44455 non-null  float64
 35  Nahariyya          44456 non-null  float64
 36  Jerusalem          44460 non-null  float64
dtypes: float64(36), str(1)
memory usage: 13.6 MB

In [8]:
temperature.describe()

,Vancouver,Portland,San Francisco,Seattle,Los Angeles,San Diego,Las Vegas,Phoenix,Albuquerque,Denver,San Antonio,Dallas,Houston,Kansas City,Minneapolis,Saint Louis,Chicago,Nashville,Indianapolis,Atlanta,Detroit,Jacksonville,Charlotte,Miami,Pittsburgh,Toronto,Philadelphia,New York,Montreal,Boston,Beersheba,Tel Aviv District,Eilat,Haifa,Nahariyya,Jerusalem
count,44458.000000,45252.000000,44460.000000,45250.000000,45250.000000,45252.000000,45252.000000,45250.000000,45252.000000,45252.000000,45252.000000,45249.000000,45250.000000,45252.000000,45240.000000,45252.000000,45250.000000,45251.000000,45246.000000,45247.000000,45252.000000,45252.000000,45250.000000,44448.000000,45250.000000,45252.000000,45250.000000,44460.000000,45250.000000,45250.000000,44455.000000,44460.000000,44461.000000,44455.000000,44456.000000,44460.000000
mean,283.862654,284.992929,288.155821,284.409626,290.846116,290.215044,292.424887,295.493358,285.617856,282.839407,293.785646,292.375872,294.204268,286.641663,280.700489,286.675947,283.350573,288.566306,284.771904,289.772673,282.971668,294.333380,288.897483,298.181274,284.053939,281.941241,285.374168,285.400406,280.343010,283.779823,291.521986,294.512307,296.497276,295.266398,294.094803,293.184253
std,6.640131,7.452438,5.332862,6.547986,6.460823,5.889992,10.829522,9.916743,9.853484,10.673464,8.303688,9.464741,7.766719,11.169761,12.774979,10.938867,10.997137,9.883590,11.043634,8.703643,11.034481,6.682162,9.133072,4.190185,10.453927,10.547226,10.242377,10.220932,11.953626,9.802499,7.821815,6.676412,8.852984,6.324566,6.304118,7.093583
min,245.150000,262.370000,272.300000,263.780000,266.503667,265.783333,260.561333,266.059000,255.042333,247.727667,265.050000,261.610333,267.570000,249.556333,242.336667,251.050000,248.890000,256.326333,244.866333,259.500000,243.483333,268.610000,255.658333,275.233333,249.422667,247.300000,250.390000,250.774000,243.300000,249.540000,272.179000,271.049000,271.150000,271.150000,268.682000,272.974000
25%,279.160000,279.850000,284.670000,279.830000,286.380000,286.254750,283.920000,287.680000,277.970000,275.060000,288.600000,285.720000,289.361125,278.300000,271.790000,278.260000,275.172450,281.220000,276.110000,283.320417,274.690000,290.040875,282.010000,296.030000,275.857427,274.260000,277.350636,277.370000,271.971750,276.090000,285.366623,289.450000,289.734000,290.467333,289.881833,287.524279
50%,283.450000,284.320000,287.610000,283.940000,290.530000,290.118750,292.027486,295.586667,286.120000,282.970667,295.184250,293.563000,295.660000,288.062000,281.639000,287.766500,283.940667,289.970333,285.929333,291.050000,283.540000,295.640000,290.120000,298.880000,285.220000,282.350000,285.927583,285.870000,281.109000,284.133250,290.932667,294.900000,296.150000,294.820000,294.150000,292.996000
75%,288.600785,289.451750,291.015167,288.530000,295.080000,294.107542,300.835000,303.050000,292.835643,290.680000,299.490000,299.550000,299.690000,295.630000,291.310000,295.560000,292.280000,296.140250,293.960000,296.290000,292.231250,299.140000,295.770000,300.992375,292.580000,290.659500,293.796000,293.760000,290.369583,291.620000,297.270000,299.800000,303.150000,299.660000,298.930000,299.150000
max,307.000000,312.520000,313.620000,307.300000,315.470000,313.360000,318.640000,321.220000,312.710000,313.750000,313.660000,314.400000,312.910000,310.970000,308.240000,311.590000,308.480000,309.150000,312.040000,310.760000,308.050000,310.150000,310.900000,308.680000,306.290000,307.280000,308.000000,310.240000,307.880000,308.000000,314.820000,320.930000,320.150000,320.930000,313.150000,317.040000

In [9]:
temperature.isnull().sum()

datetime               0
Vancouver            795
Portland               1
San Francisco        793
Seattle                3
Los Angeles            3
San Diego              1
Las Vegas              1
Phoenix                3
Albuquerque            1
Denver                 1
San Antonio            1
Dallas                 4
Houston                3
Kansas City            1
Minneapolis           13
Saint Louis            1
Chicago                3
Nashville              2
Indianapolis           7
Atlanta                6
Detroit                1
Jacksonville           1
Charlotte              3
Miami                805
Pittsburgh             3
Toronto                1
Philadelphia           3
New York             793
Montreal               3
Boston                 3
Beersheba            798
Tel Aviv District    793
Eilat                792
Haifa                798
Nahariyya            797
Jerusalem            793
dtype: int64

In [10]:
temperature.duplicated().sum()

np.int64(0)