In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

print("Libraries Imported Successfully")

C:\Users\Darshan V\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

Libraries Imported Successfully

In [3]:
temperature = pd.read_csv("../../data/raw/weather/temperature.csv")
humidity = pd.read_csv("../../data/raw/weather/humidity.csv")
pressure = pd.read_csv("../../data/raw/weather/pressure.csv")
wind = pd.read_csv("../../data/raw/weather/wind_direction.csv")
description = pd.read_csv("../../data/raw/weather/weather_description.csv")

print("All datasets loaded successfully!")

All datasets loaded successfully!

In [4]:
temperature_long = temperature.melt(
    id_vars="datetime",
    var_name="city",
    value_name="temperature"
)

temperature_long.head()

              datetime       city  temperature
0  2012-10-01 12:00:00  Vancouver          NaN
1  2012-10-01 13:00:00  Vancouver   284.630000
2  2012-10-01 14:00:00  Vancouver   284.629041
3  2012-10-01 15:00:00  Vancouver   284.626998
4  2012-10-01 16:00:00  Vancouver   284.624955

In [5]:
humidity_long = humidity.melt(
    id_vars="datetime",
    var_name="city",
    value_name="humidity"
)

In [6]:
pressure_long = pressure.melt(
    id_vars="datetime",
    var_name="city",
    value_name="pressure"
)

In [7]:
wind_long = wind.melt(
    id_vars="datetime",
    var_name="city",
    value_name="wind_direction"
)

In [8]:
description_long = description.melt(
    id_vars="datetime",
    var_name="city",
    value_name="weather_description"
)

In [9]:
weather = temperature_long.merge(
    humidity_long,
    on=["datetime", "city"]
)

weather = weather.merge(
    pressure_long,
    on=["datetime", "city"]
)

weather = weather.merge(
    wind_long,
    on=["datetime", "city"]
)

weather = weather.merge(
    description_long,
    on=["datetime", "city"]
)

weather.head()

,datetime,city,temperature,humidity,pressure,wind_direction,weather_description
0,2012-10-01 12:00:00,Vancouver,NaN,NaN,NaN,NaN,NaN
1,2012-10-01 13:00:00,Vancouver,284.630000,76.0,NaN,0.0,mist
2,2012-10-01 14:00:00,Vancouver,284.629041,76.0,NaN,6.0,broken clouds
3,2012-10-01 15:00:00,Vancouver,284.626998,76.0,NaN,20.0,broken clouds
4,2012-10-01 16:00:00,Vancouver,284.624955,77.0,NaN,34.0,broken clouds

In [10]:
print(weather.shape)

(1629108, 7)

In [12]:
weather.to_csv(
    "../../data/intermediate/weather/weather_master.csv",
    index=False
)

print("Weather Master Dataset Saved Successfully!")

Weather Master Dataset Saved Successfully!