In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

weather = pd.read_csv(
    "../../data/intermediate/weather/weather_master.csv"
)

print("Weather Dataset Loaded Successfully!")

C:\Users\Darshan V\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

Weather Dataset Loaded Successfully!

In [2]:
weather.head()

,datetime,city,temperature,humidity,pressure,wind_direction,weather_description
0,2012-10-01 12:00:00,Vancouver,NaN,NaN,NaN,NaN,NaN
1,2012-10-01 13:00:00,Vancouver,284.630000,76.0,NaN,0.0,mist
2,2012-10-01 14:00:00,Vancouver,284.629041,76.0,NaN,6.0,broken clouds
3,2012-10-01 15:00:00,Vancouver,284.626998,76.0,NaN,20.0,broken clouds
4,2012-10-01 16:00:00,Vancouver,284.624955,77.0,NaN,34.0,broken clouds

In [3]:
weather.tail()

,datetime,city,temperature,humidity,pressure,wind_direction,weather_description
1629103,2017-11-29 20:00:00,Jerusalem,NaN,NaN,NaN,NaN,NaN
1629104,2017-11-29 21:00:00,Jerusalem,NaN,NaN,NaN,NaN,NaN
1629105,2017-11-29 22:00:00,Jerusalem,NaN,NaN,NaN,NaN,NaN
1629106,2017-11-29 23:00:00,Jerusalem,NaN,NaN,NaN,NaN,NaN
1629107,2017-11-30 00:00:00,Jerusalem,NaN,NaN,NaN,NaN,NaN

In [4]:
weather.shape

(1629108, 7)

In [5]:
weather.columns

Index(['datetime', 'city', 'temperature', 'humidity', 'pressure',
       'wind_direction', 'weather_description'],
      dtype='str')

In [6]:
weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 1629108 entries, 0 to 1629107
Data columns (total 7 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   datetime             1629108 non-null  str
 1   city                 1629108 non-null  str
 2   temperature          1621078 non-null  float64
 3   humidity             1600457 non-null  float64
 4   pressure             1612428 non-null  float64
 5   wind_direction       1621133 non-null  float64
 6   weather_description  1621153 non-null  str
dtypes: float64(4), str(3)
memory usage: 148.9 MB

In [7]:
weather.describe(include="all")

,datetime,city,temperature,humidity,pressure,wind_direction,weather_description
count,1629108,1629108,1.621078e+06,1.600457e+06,1.612428e+06,1.621133e+06,1621153
unique,45253,36,NaN,NaN,NaN,NaN,54
top,2012-10-01 12:00:00,Vancouver,NaN,NaN,NaN,NaN,sky is clear
freq,36,45253,NaN,NaN,NaN,NaN,651226
mean,NaN,NaN,2.885958e+02,6.813581e+01,1.016521e+03,1.829256e+02,NaN
std,NaN,NaN,1.035149e+01,2.244515e+01,1.556569e+01,1.060446e+02,NaN
min,NaN,NaN,2.423367e+02,5.000000e+00,8.000000e+02,0.000000e+00,NaN
25%,NaN,NaN,2.818840e+02,5.300000e+01,1.012000e+03,9.400000e+01,NaN
50%,NaN,NaN,2.895800e+02,7.200000e+01,1.017000e+03,1.900000e+02,NaN
75%,NaN,NaN,2.962500e+02,8.700000e+01,1.024000e+03,2.700000e+02,NaN
max,NaN,NaN,3.212200e+02,1.000000e+02,1.100000e+03,3.600000e+02,NaN

In [8]:
weather.duplicated().sum()

np.int64(0)

In [9]:
weather["datetime"] = pd.to_datetime(weather["datetime"])

In [10]:
print(weather["datetime"].min())
print(weather["datetime"].max())

2012-10-01 12:00:00
2017-11-30 00:00:00

In [11]:
weather["city"].nunique()

36

In [12]:
weather["city"].unique()

<ArrowStringArray>
[        'Vancouver',          'Portland',     'San Francisco',
           'Seattle',       'Los Angeles',         'San Diego',
         'Las Vegas',           'Phoenix',       'Albuquerque',
            'Denver',       'San Antonio',            'Dallas',
           'Houston',       'Kansas City',       'Minneapolis',
       'Saint Louis',           'Chicago',         'Nashville',
      'Indianapolis',           'Atlanta',           'Detroit',
      'Jacksonville',         'Charlotte',             'Miami',
        'Pittsburgh',           'Toronto',      'Philadelphia',
          'New York',          'Montreal',            'Boston',
         'Beersheba', 'Tel Aviv District',             'Eilat',
             'Haifa',         'Nahariyya',         'Jerusalem']
Length: 36, dtype: str

In [13]:
missing = weather.isnull().sum().to_frame(name="Missing Values")

missing["Percentage"] = (
    missing["Missing Values"] / len(weather) * 100
).round(2)

missing

                     Missing Values  Percentage
datetime                          0        0.00
city                              0        0.00
temperature                    8030        0.49
humidity                      28651        1.76
pressure                      16680        1.02
wind_direction                 7975        0.49
weather_description            7955        0.49

In [14]:
weather["weather_description"].value_counts()

weather_description
sky is clear                           651226
broken clouds                          169652
scattered clouds                       145290
overcast clouds                        137604
few clouds                             135187
light rain                             129248
mist                                    99624
moderate rain                           43531
haze                                    24506
fog                                     16444
light snow                              14385
heavy intensity rain                    14171
light intensity drizzle                  8122
proximity thunderstorm                   5364
light intensity shower rain              3870
snow                                     3188
thunderstorm                             3102
heavy snow                               2822
drizzle                                  2479
proximity shower rain                    2401
smoke                                    2064
dust                                     1201
thunderstorm with light rain             1185
very heavy rain                          1056
light shower snow                         998
thunderstorm with rain                    547
heavy shower snow                         405
thunderstorm with heavy rain              397
shower rain                               232
heavy intensity drizzle                   229
proximity thunderstorm with rain          133
squalls                                   112
sand                                       70
freezing rain                              52
light intensity drizzle rain               43
light rain and snow                        40
heavy intensity shower rain                34
shower snow                                24
light shower sleet                         24
thunderstorm with light drizzle            22
proximity thunderstorm with drizzle        15
thunderstorm with drizzle                   8
proximity sand/dust whirls                  7
proximity moderate rain                     7
sand/dust whirls                            7
ragged shower rain                          5
sleet                                       4
shower drizzle                              4
volcanic ash                                3
ragged thunderstorm                         2
thunderstorm with heavy drizzle             2
tornado                                     2
heavy thunderstorm                          2
rain and snow                               1
Name: count, dtype: int64