In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

C:\Users\Darshan V\AppData\Roaming\Python\Python313\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
weather = pd.read_csv(
    "../../data/intermediate/weather/weather_master.csv"
)

print("Weather Dataset Loaded Successfully")

Weather Dataset Loaded Successfully

In [4]:
print("Shape:", weather.shape)

weather.head()

Shape: (1629108, 7)

,datetime,city,temperature,humidity,pressure,wind_direction,weather_description
0,2012-10-01 12:00:00,Vancouver,NaN,NaN,NaN,NaN,NaN
1,2012-10-01 13:00:00,Vancouver,284.630000,76.0,NaN,0.0,mist
2,2012-10-01 14:00:00,Vancouver,284.629041,76.0,NaN,6.0,broken clouds
3,2012-10-01 15:00:00,Vancouver,284.626998,76.0,NaN,20.0,broken clouds
4,2012-10-01 16:00:00,Vancouver,284.624955,77.0,NaN,34.0,broken clouds

In [5]:
weather["datetime"] = pd.to_datetime(weather["datetime"])

print(weather["datetime"].dtype)

datetime64[us]

In [6]:
missing = weather.isnull().sum().to_frame(name="Missing Values")

missing["Percentage"] = (
    missing["Missing Values"] / len(weather) * 100
).round(2)

missing

                     Missing Values  Percentage
datetime                          0        0.00
city                              0        0.00
temperature                    8030        0.49
humidity                      28651        1.76
pressure                      16680        1.02
wind_direction                 7975        0.49
weather_description            7955        0.49

In [7]:
weather = weather.sort_values(["city", "datetime"])

In [8]:
weather["temperature"] = (
    weather.groupby("city")["temperature"]
    .transform(lambda x: x.interpolate())
)

In [9]:
weather["humidity"] = (
    weather.groupby("city")["humidity"]
    .transform(lambda x: x.interpolate())
)

In [10]:
weather["pressure"] = (
    weather.groupby("city")["pressure"]
    .transform(lambda x: x.interpolate())
)

In [11]:
weather["weather_description"] = (
    weather.groupby("city")["weather_description"]
    .transform(lambda x: x.ffill().bfill())
)

In [12]:
weather.isnull().sum()

datetime                  0
city                      0
temperature              35
humidity                 35
pressure                 55
wind_direction         7975
weather_description       0
dtype: int64

In [13]:
weather["temperature"] = weather["temperature"] - 273.15

In [14]:
weather["temperature"].describe()

count    1.629073e+06
mean     1.547026e+01
std      1.034028e+01
min     -3.081333e+01
25%      8.780000e+00
50%      1.645153e+01
75%      2.312000e+01
max      4.807000e+01
Name: temperature, dtype: float64

In [15]:
weather[
    (weather["humidity"] < 0)
    | (weather["humidity"] > 100)
]

Empty DataFrame
Columns: [datetime, city, temperature, humidity, pressure, wind_direction, weather_description]
Index: []

In [16]:
weather[
    (weather["pressure"] < 800)
    | (weather["pressure"] > 1100)
]

Empty DataFrame
Columns: [datetime, city, temperature, humidity, pressure, wind_direction, weather_description]
Index: []

In [17]:
weather[
    (weather["wind_direction"] < 0)
    | (weather["wind_direction"] > 360)
]

Empty DataFrame
Columns: [datetime, city, temperature, humidity, pressure, wind_direction, weather_description]
Index: []

In [18]:
print(
    "Duplicate Records:",
    weather.duplicated().sum()
)

Duplicate Records: 0

In [19]:
weather.info()

<class 'pandas.DataFrame'>
Index: 1629108 entries, 362024 to 45252
Data columns (total 7 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   datetime             1629108 non-null  datetime64[us]
 1   city                 1629108 non-null  str
 2   temperature          1629073 non-null  float64
 3   humidity             1629073 non-null  float64
 4   pressure             1629053 non-null  float64
 5   wind_direction       1621133 non-null  float64
 6   weather_description  1629108 non-null  str
dtypes: datetime64[us](1), float64(4), str(2)
memory usage: 131.9 MB

In [21]:
weather.to_csv(
    "../../data/processed/weather/weather_processed.csv",
    index=False
)

print("Processed Weather Dataset Saved Successfully!")

Processed Weather Dataset Saved Successfully!