In [39]:
# ==========================================================
# Hybrid AI-Based Risk Assessment Engine
# Intelligent Flight Operations Analytics
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

plt.style.use("ggplot")

print("="*70)
print("Hybrid AI-Based Risk Assessment Engine")
print("="*70)

======================================================================
Hybrid AI-Based Risk Assessment Engine
======================================================================

In [40]:
# ==========================================================
# Load Datasets
# ==========================================================

elm_df = pd.read_csv("../data/final/elm_anomaly_detection_dataset.csv")

weather_df = pd.read_csv("../data/final/weather_cross_dataset_feature_engineered.csv")

delay_df = pd.read_csv("../data/final/delay_cross_dataset_feature_engineered.csv")

In [41]:
print("ELM Dataset Shape :", elm_df.shape)
print("Weather Dataset Shape :", weather_df.shape)
print("Delay Dataset Shape :", delay_df.shape)

ELM Dataset Shape : (7516, 89)
Weather Dataset Shape : (1629108, 21)
Delay Dataset Shape : (3000000, 44)

In [42]:
print("="*60)
print("ELM DATASET")
print("="*60)

display(elm_df.head())

print(elm_df.shape)

============================================================
ELM DATASET
============================================================

,icao24,callsign,origin_country,time_position,last_constant,longitude,latitude,baro_altitude,on_ground,velocity,true_track,vertical_rate,geo_altitude,squawk,spi,position_source,flight_phase,speed_category,altitude_band,vertical_movement,heading_direction,operational_risk,N-NUMBER,SERIAL NUMBER,MFR MDL CODE,ENG MFR MDL,YEAR MFR,TYPE REGISTRANT,LAST ACTION DATE,CERT ISSUE DATE,CERTIFICATION,TYPE AIRCRAFT,TYPE ENGINE,STATUS CODE,MODE S CODE,AIR WORTH DATE,EXPIRATION DATE,UNIQUE ID,MODE S CODE HEX,MANUFACTURER,AIRCRAFT_MODEL,AIRCRAFT_TYPE_CODE,ENGINE_TYPE_CODE,AIRCRAFT_CATEGORY,BUILD_CERTIFICATE,NUMBER_OF_ENGINES,SEAT_CAPACITY,WEIGHT_CLASS,CRUISE_SPEED,TYPE_CERTIFICATE,CERTIFICATE_HOLDER,Aircraft_Age,Aircraft_Age_Category,Engine_Configuration,Seat_Capacity_Category,Weight_Category,Cruise_Speed_Category,Manufacturer_Group,Aircraft_Size_Category,distance_to_airport_km,nearest_ident,nearest_name,nearest_municipality,nearest_iso_country,nearest_airport_size,nearest_airport_category,nearest_airport_importance,nearest_latitude_deg,nearest_longitude_deg,nearest_lat_rad,nearest_lon_rad,datetime,Distance_Risk_Level,Airport_Operational_Profile,Aircraft_Operational_Capability,Operational_Complexity_Index,Operational_Complexity_Level,Flight_Operational_Score,Flight_Operational_Priority,Smart_Alert_Priority,Information_Filter_Level,Decision_Support_Recommendation,GMM_Cluster,GMM_Log_Likelihood,GMM_Anomaly_Score,GMM_Anomaly_Label,ELM_Reconstruction_Error,ELM_Anomaly_Score,ELM_Anomaly_Label
0,80162D,AXB848,India,1.767745e+09,1767745048,52.7391,25.4425,9608.82,False,257.34,119.59,5.20,9829.80,3112.0,False,0,Climb,Cruise Speed,High Altitude,Climbing,East,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.199726,OMAS,Das Island Airport,Das Island,AE,Small,Local,Low,25.138234,52.874429,0.438745,0.922833,2026-01-07 00:17:28,Remote,Local Airport,Unknown,7,Medium,6,Low,Low,Background Monitoring,Background Monitoring,0,-0.413259,24.597643,Normal,0.026762,0.026762,Normal
1,AE1FA0,72209,United States,1.767745e+09,1767745047,-84.9380,38.1463,571.50,False,73.38,12.96,0.33,487.68,NaN,False,0,Cruise,Low Speed,Low Altitude,Level Flight,North,Low,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.518443,05KT,High Point Farm Airport,Frankfort,US,Small,Local,Low,38.187091,-84.930110,0.666490,-1.482310,2026-01-07 00:17:27,Close,Local Airport,Unknown,6,Medium,8,Medium,Medium,Standard Monitoring,Routine Monitoring,9,10.915888,13.268496,Normal,0.001748,0.001748,Normal
2,AC96B8,AAL1175,United States,1.767745e+09,1767745048,-102.0238,34.0962,10363.20,False,196.90,291.13,0.00,10683.24,NaN,False,0,Cruise,Cruise Speed,Cruise Altitude,Level Flight,West,Low,910AN,29512,13844CB,13802.0,1999.0,3.0,2023-10-20,1999-05-27,1T,5.0,5.0,V,53113270.0,1999-05-25,2030-04-30,927071.0,AC96B8,BOEING,737-823,5.0,5.0,1.0,0.0,2.0,162.0,CLASS 3,0.0,,...,27.0,Mid-Life,Twin Engine,Medium Commercial,Heavy,Unknown,Commercial,Narrow-Body,51.550924,1TX5,Laney Farm Airport,Hale Center,US,Small,Local,Low,34.126017,-101.908751,0.595611,-1.778643,2026-01-07 00:17:28,Moderate,Local Airport,High Capability,8,Medium,9,Medium,Medium,Standard Monitoring,Routine Monitoring,7,14.991280,9.193104,Normal,0.001536,0.001536,Normal
3,C81BD3,ZKAMK,New Zealand,1.767745e+09,1767744917,174.5408,-35.8060,624.84,False,56.90,165.34,0.65,670.56,NaN,False,0,Cruise,Low Speed,Low Altitude,Level Flight,South,Low,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.487628,NZ-0085,Tahere Airstrip,Whareora,NZ,Small,Local,Low,-35.696260,174.436410,-0.623017,3.044490,2026-01-07 00:15:17,Close,Local Airport,Unknown,6,Medium,8,Medium,Medium,Standard Monitoring,Routine Monitoring,15,2.057020,22.127363,Normal,0.008986,0.008986,Normal
4,AA56DB,UAL2447,United States,1.767745e+09,1767745048,-102.7402,37.4696,10972.80,False,200.08,327.49,0.00,11155.68,NaN,False,0,Cruise,Cruise Speed,Cruise Altitude,Level Flight,North,Low,76529,31652,13844BZ,13073.0,2010.0,3.0,2023-09-22,2010-12-29,1T,5.0,5.0,V,52453333.0,2010-12-23,2029-12-31,1060884.0,AA56DB,BOEING,737-824,5.0,5.0,1.0,0.0,2.0,149.0,CLASS 3,0.0,,...,16.0,Mid-Life,Twin Engine,Medium Commercial,Heavy,Unknown,Commercial,Narrow-Body,66.500547,K8V7,Springfield Municipal Airport,Springfield,US,Small,Local,Low,37.458698,-102.617996,0.653778,-1.791022,2026-01-07 00:17:28,Moderate,Local Airport,High Capability,8,Medium,9,Medium,Medium,Standard Monitoring,Routine Monitoring,7,14.705517,9.478866,Normal,0.001448,0.001448,Normal

(7516, 89)

In [43]:
print("="*60)
print("WEATHER DATASET")
print("="*60)

display(weather_df.head())

print(weather_df.shape)

============================================================
WEATHER DATASET
============================================================

,datetime,city,temperature,humidity,pressure,wind_direction,weather_description,temperature_category,humidity_category,pressure_category,wind_direction_category,rain_indicator,snow_indicator,storm_indicator,fog_indicator,cloud_category,weather_severity,weather_risk_score,Weather_Operational_Severity,Weather_Disruption_Level,Weather_Alert_Priority
0,2012-10-01 12:00:00,Albuquerque,11.970000,50.0,1024.0,360.0,sky is clear,Cool,Medium,Normal,North,0,0,0,0,Clear,Low,1,Low,Minimal,Routine
1,2012-10-01 13:00:00,Albuquerque,11.970000,50.0,1024.0,360.0,sky is clear,Cool,Medium,Normal,North,0,0,0,0,Clear,Low,1,Low,Minimal,Routine
2,2012-10-01 14:00:00,Albuquerque,12.004558,49.0,1024.0,360.0,sky is clear,Cool,Medium,Normal,North,0,0,0,0,Clear,Low,1,Low,Minimal,Routine
3,2012-10-01 15:00:00,Albuquerque,12.083952,49.0,1024.0,360.0,sky is clear,Cool,Medium,Normal,North,0,0,0,0,Clear,Low,1,Low,Minimal,Routine
4,2012-10-01 16:00:00,Albuquerque,12.163345,49.0,1024.0,360.0,sky is clear,Cool,Medium,Normal,North,0,0,0,0,Clear,Low,1,Low,Minimal,Routine

(1629108, 21)

In [44]:
print("="*60)
print("DELAY DATASET")
print("="*60)

display(delay_df.head())

print(delay_df.shape)

============================================================
DELAY DATASET
============================================================

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT,TOTAL_DELAY,DELAY_SEVERITY,DELAY_CATEGORY,FLIGHT_PERFORMANCE_INDEX,OPERATIONAL_DISRUPTION,AIRLINE_RELIABILITY,AIRPORT_DELAY_CATEGORY,SEASON,TIME_OF_DAY,Delay_Operational_Severity,Airline_Reliability_Profile,Delay_Alert_Priority
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,0.0,0.0,0.0,0.0,0.0,-18.0,No Delay,Early,100.0,0,Medium,Medium Delay,Winter,Morning,Low,Average,Routine
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,0.0,0.0,0.0,0.0,0.0,-11.0,No Delay,On Time,100.0,0,High,Medium Delay,Autumn,Night,Low,Reliable,Routine
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,0.0,0.0,0.0,0.0,0.0,6.0,No Delay,On Time,100.0,0,Medium,Medium Delay,Summer,Morning,Low,Average,Routine
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0,23.0,Moderate,Delayed,76.0,0,High,Medium Delay,Spring,Afternoon,Medium,Reliable,Monitor
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0.0,NaN,0.0,181.0,182.0,153.0,985.0,0.0,0.0,0.0,0.0,0.0,-3.0,No Delay,On Time,100.0,0,Medium,Medium Delay,Winter,Evening,Low,Average,Routine

(3000000, 44)

In [45]:
print("="*60)
print("Missing Values")
print("="*60)

print("\nELM")
print(elm_df.isnull().sum().sort_values(ascending=False).head(10))

print("\nWeather")
print(weather_df.isnull().sum().sort_values(ascending=False).head(10))

print("\nDelay")
print(delay_df.isnull().sum().sort_values(ascending=False).head(10))

============================================================
Missing Values
============================================================

ELM
squawk             4286
Aircraft_Age       3255
YEAR MFR           3255
ENG MFR MDL        3201
AIR WORTH DATE     3201
CERTIFICATION      3189
EXPIRATION DATE    3055
CERT ISSUE DATE    3055
SERIAL NUMBER      3049
TYPE REGISTRANT    3049
dtype: int64

Weather
pressure_category       2
city                    0
temperature             0
humidity                0
datetime                0
pressure                0
wind_direction          0
temperature_category    0
weather_description     0
humidity_category       0
dtype: int64

Delay
CANCELLATION_CODE    2920860
AIR_TIME               86198
ARR_DELAY              86198
ELAPSED_TIME           86198
WHEELS_ON              79944
TAXI_IN                79944
ARR_TIME               79942
TAXI_OUT               78806
WHEELS_OFF             78806
DEP_DELAY              77644
dtype: int64

In [46]:
behaviour_df = elm_df[[
    "GMM_Anomaly_Score",
    "ELM_Anomaly_Score",
    "Operational_Complexity_Index",
    "Airport_Operational_Profile",
    "Aircraft_Operational_Capability"
]].copy()

In [47]:
behaviour_df.head()

,GMM_Anomaly_Score,ELM_Anomaly_Score,Operational_Complexity_Index,Airport_Operational_Profile,Aircraft_Operational_Capability
0,24.597643,0.026762,7,Local Airport,Unknown
1,13.268496,0.001748,6,Local Airport,Unknown
2,9.193104,0.001536,8,Local Airport,High Capability
3,22.127363,0.008986,6,Local Airport,Unknown
4,9.478866,0.001448,8,Local Airport,High Capability

In [48]:
behaviour_df.describe().T

,count,mean,std,min,25%,50%,75%,max
GMM_Anomaly_Score,7516.0,17.964940,7.468599,0.000000,12.303949,18.169104,24.128063,46.442023
ELM_Anomaly_Score,7516.0,0.017461,0.040174,0.000329,0.004562,0.009046,0.019274,1.670845
Operational_Complexity_Index,7516.0,6.912986,1.325681,4.000000,6.000000,7.000000,8.000000,11.000000

In [49]:
scaler = MinMaxScaler()

behaviour_df[[
    "GMM_Anomaly_Score",
    "ELM_Anomaly_Score",
    "Operational_Complexity_Index"
]] = scaler.fit_transform(

    behaviour_df[[
        "GMM_Anomaly_Score",
        "ELM_Anomaly_Score",
        "Operational_Complexity_Index"
    ]]
)

In [50]:
elm_df["Airport_Operational_Profile"].value_counts()

Airport_Operational_Profile
Local Airport    6374
Major Hub         854
Regional Hub      288
Name: count, dtype: int64

In [51]:
airport_map = {

    "Local Airport": 1,

    "Regional Hub": 2,

    "Major Hub": 3

}

In [52]:
elm_df["Aircraft_Operational_Capability"].value_counts()

Aircraft_Operational_Capability
Unknown                3049
High Capability        2070
Light Capability       1616
Medium Capability       758
Standard Capability      23
Name: count, dtype: int64

In [53]:
aircraft_map = {

    "Unknown": 0,

    "Light Capability": 1,

    "Medium Capability": 2,

    "Standard Capability": 3,

    "High Capability": 4

}

In [54]:
behaviour_df["Airport_Profile_Score"] = (
    elm_df["Airport_Operational_Profile"]
    .map(airport_map)
)

behaviour_df["Aircraft_Capability_Score"] = (
    elm_df["Aircraft_Operational_Capability"]
    .map(aircraft_map)
)

In [55]:
behaviour_df[
    [
        "Airport_Profile_Score",
        "Aircraft_Capability_Score"
    ]
] = scaler.fit_transform(

    behaviour_df[
        [
            "Airport_Profile_Score",
            "Aircraft_Capability_Score"
        ]
    ]
)

In [56]:
behaviour_df["Behavioural_Intelligence_Score"] = (

      behaviour_df["GMM_Anomaly_Score"] * 0.30

    + behaviour_df["ELM_Anomaly_Score"] * 0.30

    + behaviour_df["Operational_Complexity_Index"] * 0.20

    + behaviour_df["Airport_Profile_Score"] * 0.10

    + behaviour_df["Aircraft_Capability_Score"] * 0.10

)

In [57]:
behaviour_df["Behavioural_Intelligence_Score"].describe()

count    7516.000000
mean        0.253819
std         0.088786
min         0.050735
25%         0.175581
50%         0.251577
75%         0.298672
max         0.630520
Name: Behavioural_Intelligence_Score, dtype: float64

In [58]:
elm_df["Airport_Operational_Profile"].value_counts()

elm_df["Aircraft_Operational_Capability"].value_counts()

Aircraft_Operational_Capability
Unknown                3049
High Capability        2070
Light Capability       1616
Medium Capability       758
Standard Capability      23
Name: count, dtype: int64