In [1]:
import pandas as pd
aircraft = pd.read_csv(
    "../../data/processed/aircraft/aircraft_metadata_processed.csv",
    parse_dates=[
        "LAST ACTION DATE",
        "CERT ISSUE DATE",
        "AIR WORTH DATE",
        "EXPIRATION DATE"
    ]
)

acftref = pd.read_csv(
    "../../data/raw/aircraft/ACFTREF.txt",
    low_memory=False
)

print(acftref.shape)

acftref.head()

(93860, 14)

,CODE,MFR,MODEL,TYPE-ACFT,TYPE-ENG,AC-CAT,BUILD-CERT-IND,NO-ENG,NO-SEATS,AC-WEIGHT,SPEED,TC-DATA-SHEET,TC-DATA-HOLDER,Unnamed: 13
0,0020901,AAR AIRLIFT GROUP INC,UH-60A,6,3,1,0,2,15,CLASS 3,0,,...,NaN
1,0030109,EXLINE ACE-C,ACE-C,4,1,1,1,1,1,CLASS 1,82,,...,NaN
2,003010D,DELEBAUGH,P,4,1,1,1,1,1,CLASS 1,82,,...,NaN
3,003010H,DAL PORTO,BABY ACE D,4,1,1,1,1,1,CLASS 1,82,,...,NaN
4,003010P,DUNN,BABY ACE,4,1,1,1,1,1,CLASS 1,82,,...,NaN

In [2]:
acftref.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93860 entries, 0 to 93859
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CODE            93860 non-null  object
 1   MFR             93860 non-null  object
 2   MODEL           93860 non-null  object
 3   TYPE-ACFT       93860 non-null  object
 4   TYPE-ENG        93860 non-null  int64
 5   AC-CAT          93860 non-null  int64
 6   BUILD-CERT-IND  93860 non-null  int64
 7   NO-ENG          93860 non-null  int64
 8   NO-SEATS        93860 non-null  int64
 9   AC-WEIGHT       93860 non-null  object
 10  SPEED           93860 non-null  int64
 11  TC-DATA-SHEET   93860 non-null  object
 12  TC-DATA-HOLDER  93860 non-null  object
 13  Unnamed: 13     0 non-null      float64
dtypes: float64(1), int64(6), object(7)
memory usage: 10.0+ MB

In [3]:
acftref.columns

Index(['CODE', 'MFR', 'MODEL', 'TYPE-ACFT', 'TYPE-ENG', 'AC-CAT',
       'BUILD-CERT-IND', 'NO-ENG', 'NO-SEATS', 'AC-WEIGHT', 'SPEED',
       'TC-DATA-SHEET', 'TC-DATA-HOLDER', 'Unnamed: 13'],
      dtype='object')

In [4]:
acftref = acftref.drop(columns=["Unnamed: 13"])

In [5]:
print("Duplicate Codes:", acftref["CODE"].duplicated().sum())

Duplicate Codes: 0

In [6]:
print(aircraft["MFR MDL CODE"].dtype)

print(acftref["CODE"].dtype)

object
object

In [7]:
aircraft_metadata = aircraft.merge(
    acftref,
    left_on="MFR MDL CODE",
    right_on="CODE",
    how="left"
)

In [8]:

print("Merged Aircraft Dataset")


print(aircraft_metadata.shape)

Merged Aircraft Dataset
(314417, 30)

In [9]:
aircraft_metadata.head()

,N-NUMBER,SERIAL NUMBER,MFR MDL CODE,ENG MFR MDL,YEAR MFR,TYPE REGISTRANT,LAST ACTION DATE,CERT ISSUE DATE,CERTIFICATION,TYPE AIRCRAFT,...,TYPE-ACFT,TYPE-ENG,AC-CAT,BUILD-CERT-IND,NO-ENG,NO-SEATS,AC-WEIGHT,SPEED,TC-DATA-SHEET,TC-DATA-HOLDER
0,100,5334,7100510,17003.0,1940.0,1.0,2023-01-22,2005-05-06,1,4,...,4,1,1,0,1,2,CLASS 1,67,,...
1,10000,10000,2130004,NaN,NaN,7.0,2024-08-23,2024-08-23,NaN,4,...,4,1,1,0,1,5,CLASS 1,0,,...
2,10001,A28,9601202,67007.0,1928.0,1.0,2023-07-18,2019-02-27,1,4,...,4,1,1,0,1,3,CLASS 1,79,,...
3,10004,T18208245,2072738,NaN,NaN,7.0,2023-07-22,2013-03-12,NaN,4,...,4,2,1,0,1,4,CLASS 1,0,3A13,TEXTRON AVIATION INC ...
4,10006,BG-72,1152020,17026.0,1955.0,1.0,2023-04-21,1998-08-26,1U,4,...,4,1,1,0,1,4,CLASS 1,0,,...

In [10]:
aircraft_metadata["MFR"].isnull().sum()

np.int64(0)

In [11]:
aircraft_metadata["MODEL"].isnull().sum()

np.int64(0)

In [12]:
matched = aircraft_metadata["MFR"].notna().sum()

total = len(aircraft_metadata)

print(f"Matched Records : {matched:,}")

print(f"Total Records   : {total:,}")

print(f"Match Rate      : {(matched/total)*100:.2f}%")

Matched Records : 314,417
Total Records   : 314,417
Match Rate      : 100.00%

In [13]:
aircraft_metadata.to_csv(
    "../../data/processed/aircraft/aircraft_metadata_enriched.csv",
    index=False
)

print("Aircraft Metadata Enriched Dataset Saved Successfully")

Aircraft Metadata Enriched Dataset Saved Successfully

In [14]:
aircraft_metadata.drop(
    columns=[
        "CODE",
        "Unnamed: 13"
    ],
    inplace=True
)

KeyError: "['Unnamed: 13'] not found in axis"

In [ ]:
aircraft_metadata.rename(columns={

    "MFR": "MANUFACTURER",

    "MODEL": "AIRCRAFT_MODEL",

    "TYPE-ACFT": "AIRCRAFT_TYPE_CODE",

    "TYPE-ENG": "ENGINE_TYPE_CODE",

    "AC-CAT": "AIRCRAFT_CATEGORY",

    "BUILD-CERT-IND": "BUILD_CERTIFICATE",

    "NO-ENG": "NUMBER_OF_ENGINES",

    "NO-SEATS": "SEAT_CAPACITY",

    "AC-WEIGHT": "WEIGHT_CLASS",

    "SPEED": "CRUISE_SPEED",

    "TC-DATA-SHEET": "TYPE_CERTIFICATE",

    "TC-DATA-HOLDER": "CERTIFICATE_HOLDER"

}, inplace=True)

In [ ]:
aircraft_metadata.to_csv(
    "../../data/processed/aircraft/aircraft_metadata_final.csv",
    index=False
)

print("Final Aircraft Metadata Dataset Saved Successfully")

Final Aircraft Metadata Dataset Saved Successfully